name: Test

on:
  push:
    branches: 
      - feature/*
      - develop

defaults:
  integration-script: &integration-script
    run: |
      npm run build
      node build_release_package_json.js
      npm run integration-test
  test-integration: &test-integration
    name: Integration Tests (Test)
    <<: *integration-script
    if: contains(github.ref, 'feature')
    env:
      API_KEY: ${{ secrets.TEST_API_KEY }}
      USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      BASE_URL: ${{ secrets.TEST_BASE_URL }}
  stage-integration: &stage-integration
    name: Integration Tests (Stage)
    <<: *integration-script
    if: (github.ref == develop)
    env:
      API_KEY: ${{ secrets.STAGE_API_KEY }}
      USER_EMAIL: ${{ secrets.STAGE_USER_EMAIL }}
      BASE_URL: ${{ secrets.STAGE_BASE_URL }}


jobs:
  test:
    name: Build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 10, 12]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install Deps
      run: npm install

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Unit Test
      run: npm run unit-test

    - <<: *test-integration
    - <<: *stage-integration
